version: "3.7"

services:
  traefik:
    image: "traefik:latest"
    container_name: traefik
    restart: unless-stopped
    command:
      # - --metrics
      # - --metrics.prometheus.buckets=0.1,0.3,1.2,5.0
      - --log.level=INFO
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      # - --accesslog=true
      # - --accesslog.filepath=/var/log/traefik/access.log
      - --accesslog.format=json
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --certificatesresolvers.md-resolver.acme.tlschallenge=true
      - --certificatesresolvers.md-resolver.acme.email=support@multifactor.com
      - --certificatesresolvers.md-resolver.acme.storage=/letsencrypt/acme.json
      - --entryPoints.ldap-tls.address=:636
      - --entryPoints.ldap.address=:389
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
      - "389:389"
      - "636:636"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ./certs:/letsencrypt

    depends_on:
      - api_server
      - ldap_server

    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 96M
        reservations:
          cpus: '0.25'
          memory: 32M

  interface:
    image: ghcr.io/multifactorlab/multidirectory-web-admin:latest
    container_name: multidirectory_interface
    restart: unless-stopped
    environment:
      API_URL: https://${API_DOMAIN}/api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.interface.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.interface.entrypoints=websecure"
      - "traefik.http.routers.interface.tls.certresolver=md-resolver"
      - "traefik.http.services.interface.loadbalancer.server.port=80"

  ldap_server:
    image: ghcr.io/multifactorlab/multidirectory:latest
    container_name: multidirectory-ldap
    restart: unless-stopped
    env_file:
      .env
    volumes:
      - ./logs:/app/logs
    command: bash -c "alembic upgrade head && python ."
    labels:
      - traefik.enable=true
      - traefik.tcp.routers.ldap_server.rule=HostSNI(`*`)
      - traefik.tcp.routers.ldap_server.service=ldap_server-svc
      - traefik.tcp.services.ldap_server-svc.loadbalancer.server.port=389

      # - traefik.tcp.routers.ldap_server_tls.rule=HostSNI(`*`)
      # - traefik.tcp.routers.ldap_server_tls.tls=true
      # - traefik.tcp.routers.ldap_server_tls.tls.passthrough=true
      # - traefik.tcp.routers.ldap_server_tls.entrypoints=ldap-tls
      # - traefik.tcp.routers.ldap_server_tls.tls.certresolver=md-resolver
      # - traefik.tcp.routers.ldap_server_tls.service=ldap_server_tls
      # - traefik.tcp.services.ldap_server_tls.loadbalancer.server.port=389
    depends_on:
      - postgres

  api_server:
    image: ghcr.io/multifactorlab/multidirectory:latest
    container_name: multidirectory_api
    restart: unless-stopped
    env_file:
      .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`${API_DOMAIN}`) && PathPrefix(`/api`)"
      - "traefik.http.routers.api.tls.certresolver=md-resolver"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.services.api.loadbalancer.server.port=8000"
      - "traefik.http.routers.api.service=api"
      - "traefik.http.routers.api.middlewares=api_strip"
      - "traefik.http.middlewares.api_strip.stripprefix.prefixes=/api"
      - "traefik.http.middlewares.api_strip.stripprefix.forceslash=false"

    command: bash -c "alembic upgrade head && uvicorn --factory web_app:create_app --host 0.0.0.0 --port 8000"
    depends_on:
      - postgres

  postgres:
    container_name: MD-postgres
    image: postgres
    restart: unless-stopped
    env_file:
      .env
    environment:
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    expose:
      - 5432

volumes:
  traefik:
  postgres:
  pgadmin:
